Add CI/CD pipeline 2

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -44,8 +44,13 @@ jobs:
     steps:
       - name: Update Helm Chart
         run: |
+          if [ ! -f "$HELM_CHART_PATH/Chart.yaml" ]; then
+            echo "Error: Chart.yaml не найден"
+            exit 1
+          fi
+
           sed -i "s|tag:.*|tag: ${{ github.sha }}|" "$HELM_CHART_PATH/values.yaml"
-          sed -i "s/version:.*/version: $(date +%Y%m%d.%H%M%S)/" "$HELM_CHART_PATH/Chart.yaml"
+          sed -i "s/version:.*/version: $(date +%Y%m%d.%H%M%S)/" "$HELM_CHART_PATH/Сhart.yaml"
 
       - name: Commit changes
         uses: stefanzweifel/git-auto-commit-action@v4
